### PR TITLE
Port updates to  json-config-ui-block-macro.js to staging

### PR DESCRIPTION
**Pull request by ibsoln**
from PR#183  150de64

### CODE REVIEW

**Comment by ibsoln** [comment]
I've pulled the change to this file across, but is it likely the whole PR#183 needs porting?

**Comment by mojavelinux** [comment]
I don't know what has already been ported. It's possible some of it has already been done. The main thing to bring over when upgrading Antora are the changes to the Asciidoctor extensions.

**Comment by amarantha-k** [comment]
@mojavelinux I ported updates to swagger-ui-block-macro.js to staging branch and missed the changes to json-config-ui-block-macro.js. Looking at the staging branch, other updates for Antora 2.3 seem to be available already. 
However, still need to investigate the deploy preview build failure.

**Comment by ibsoln** [comment]
> @mojavelinux I ported updates to swagger-ui-block-macro.js to staging branch and missed the changes to json-config-ui-block-macro.js. Looking at the staging branch, other updates for Antora 2.3 seem to be available already.
> However, still need to investigate the deploy preview build failure.

Thanks @amarantha-k. What are the list of failed checks about on the merge request?

**Comment by amarantha-k** [comment]
@ibsoln The logs show a GITHUB TOKEN error and I've request @mojavelinux to take a look.

**Comment by mojavelinux** [comment]
I'll have a look shortly.

**Comment by mojavelinux** [comment]
I'm going to take care of this as part of a larger change.

**Pull request closed without merging**
