### PR TITLE
DOC-7344: Updates to Contributor's Guide

### PR DESCRIPTION
**Pull request by simon-dew**
Cherry-picking #270 into staging branch

Doc issue: [DOC-7344](https://issues.couchbase.com/browse/DOC-7344)

### CODE REVIEW

**Review by RichardSmedley — APPROVED** [review]
LGTM

**Comment by mojavelinux** [comment]
Please rebase and this will once again deploy successfully.

**Comment by mojavelinux** [comment]
This PR seems to contain more than just update the contributors guide. Can you keep the changes to the build and playbook configuration separate?

**Comment by mojavelinux** [comment]
GitHub forced this issue to be closed because of a conflict with the new staging branch. Sorry about that. Can you submit a new PR?

**Comment by mojavelinux** [comment]
Nevermind. I have synced the changes. Just let me know if anything looks missing.

In the future, please don't submit changes to the contributing guide to the staging branch. The staging branch is only meant for sharing new content that is not yet ready for production, but should be on an official domain (docs-staging.couchbase.com). In almost all cases, you should be submitting a PR to the master branch. We can then backport changes periodically to staging. (Though it would be better the contribute module were not in the playbook repository at all so that it could be shared by different environments, but that's a separate task).

**Pull request closed without merging**
