### PR TITLE
Update to latest UI bundle

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux Surprised that the preview build failed when stage went through fine. Any pointers?

**Comment by mojavelinux** [comment]
It was a communication error with GitLab:

```
ERR! /usr/bin/git ls-remote -h -t https://gitlab.com/antora/xref-validator.git
```

Also note that Netlify is limiting the build to 15 minutes and we're right up against that limit. So sometimes it fails because it runs out of time (not this time though).

**Comment by amarantha-k** [comment]
Thanks!

**Comment by amarantha-k** [comment]
Merging as build was successful but timed out during post processing phase.

**Pull request merged**
