### PR TITLE
Build Kafka 3.4 docs from release/3.4 branch

### PR DESCRIPTION
**Pull request by dnault**
Motivation
----------
master branch is now being used for 4.0 development

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux I've re-run the deploy build a few times and it hits the Netlify timeout each time. Could you take a look and let me know if I'm missing anything? If it's just the Netlify timeout, then I would like to merge this PR.

**Comment by mojavelinux** [comment]
I forced it to run again after disabling the xref validator. We cannot use the xref validator in the Netlify build since Netlify does not allocate enough time for it to run.

**Comment by mojavelinux** [comment]
@amarantha-k The cloning of the tutorials repository simply takes too long to fit within the time Netlify allocates for the build. I strongly recommend reaching out to Netlify to find out why the build is so limited for a Pro Account. This is frankly ridiculous.

**Comment by mojavelinux** [comment]
I don't understand what's wrong with the PR. Netlify simply refuses to build it.

**Comment by mojavelinux** [comment]
I'll just merge and we'll deal with this build problem separately.

**Pull request merged**
