### PR TITLE
DOC-9701-staging Add new global attribute to represent SQL++

### PR DESCRIPTION
**Pull request by RayOffiah**
Added new attribute

### CODE REVIEW

**Comment by maria-robobug** [comment]
Not sure if it's due to this change from Dan, https://github.com/couchbase/docs-site/commit/a7be5a36485d400a6e4bd6010f879c9b6b9d8bb8#diff-0ede03e58603c03c400bde34263582dbb4a75248e7d1f52cdee1729c44398cabL6-L11

But let's see...

**Comment by maria-robobug** [comment]
Oooh, I can see logs now, maybe we'll see what's wrong if it fails again: https://app.netlify.com/sites/cb-docs-staging/deploys/620be3f1be5e403a4d105b38#L80
👍

**Comment by maria-robobug** [comment]
```
6:03:37 PM: Build exceeded maximum allowed runtime 
```
Well antora built things fine I think. Just seems Netlify timeout is going to be an even bigger problem...I'll merge 👍 .

**Comment by RayOffiah** [comment]
Okay, thanks for that.

I was wondering it it's attempts to run the Kroki stuff is causing a problem, since it can't reach the server. That won't help with the timeouts.

**Comment by maria-robobug** [comment]
> I was wondering it it's attempts to run the Kroki stuff is causing a problem, since it can't reach the server. That won't help with the timeouts.

It's quite possible ya know, didn't think of that... 🤔 . 
Let's keep an eye on it.

**Pull request merged**
