### PR TITLE
add extension that populates data-source-url attribute for code (source and listing) blocks

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@amarantha-k This requires a UI change to be visible. See https://github.com/couchbase/docs-ui-sandbox/pull/25

**Comment by mojavelinux** [comment]
@amarantha-k Here's an example: https://deploy-preview-216--cb-docs-sandbox.netlify.app/go-sdk/2.1/hello-world/start-using-sdk.html

View the source and look for data-source-url.

**Comment by amarantha-k** [comment]
@mojavelinux https://github.com/couchbase/docs-ui-sandbox/pull/28 has been merged and cloud-21 is available. Could you rebase your updates and also bump the UI bundle version please? Thanks.

**Comment by mojavelinux** [comment]
Yep!

**Comment by mojavelinux** [comment]
Done. And the latest version of Couchbase Server is now fixed too. (It was pulling in part of Server 7.0 before).

Note that there are still incorrect xrefs on the server landing page.

**Comment by amarantha-k** [comment]
Thanks! Will merge this PR and continue to fix the incorrect refs on the server landing page.

**Pull request merged**
