### PR TITLE
DOC-7913 removing EOS/EOL

### PR DESCRIPTION
**Pull request by RichardSmedley**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Will you be adding these to the archive site at the same time?

**Comment by amarantha-k** [comment]
@mojavelinux I see these releases on the archive branch already, submitted via [these commits](https://github.com/couchbase/docs-site/commit/c61f119cf2747c3b8e36555ddaa3cd1e5c758cc8).

**Comment by mojavelinux** [comment]
Perfect! Thanks for checking.

>

**Review by amarantha-k — APPROVED** [review]
Lgtm

**Pull request merged**
