### PR TITLE
Update landing pages for home, server, sdk

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@amarantha-k Can you rebase this against master?

**Comment by mojavelinux** [comment]
Oops, I just realized I need to sync staging with the updates from master. Hold and stay tuned.

**Comment by amarantha-k** [comment]
@mojavelinux Noted. Since staging and master are different environments, I created a new PR for staging.

**Comment by mojavelinux** [comment]
Yep. I was getting things mixed up. I'll let you know when you can rebase against *staging* :wink:

**Comment by amarantha-k** [comment]
@mojavelinux Can I rebase against staging?

**Comment by mojavelinux** [comment]
Yes please!

**Comment by amarantha-k** [comment]
@mojavelinux Done. Please take a look.

**Pull request merged**
