### PR TITLE
Update home page for archive site

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux The CSS eventually needs to be moved to docs-ui repository.

**Comment by mojavelinux** [comment]
@amarantha-k Can you use xrefs instead of absolute URLs for the links?

**Comment by amarantha-k** [comment]
If that's not a blocker, I'd prefer to do that by Monday. There are some more older SDK links that need to be included on this page.

**Comment by mojavelinux** [comment]
I think it's pretty important to stick with xrefs where possible. I can make that update for you, if you'd like. It probably wouldn't take me long.

I noticed "Node.js" is written as "Nodejs". To be consistent with other uses on the site, I think it should be the former.

**Comment by amarantha-k** [comment]
That's great if you can update the xrefs. Thanks!

**Comment by amarantha-k** [comment]
Thanks for the updates, @mojavelinux. Are we good to merge the PR?

**Comment by mojavelinux** [comment]
@amarantha-k If you're happy with the result, then yes, it's ready to merge.

**Comment by amarantha-k** [comment]
Looks good; +1 to merge.

**Comment by mojavelinux** [comment]
Okay, merging!

**Pull request merged**
