### PR TITLE
Doc 9391 – moving release/5.5, release/5.1 and release/5.0 to archive master branch

### PR DESCRIPTION
**Pull request by RayOffiah**
Moved these to the archive site in a separate PR (433)

### CODE REVIEW

**Comment by maria-robobug** [comment]
Hmm, I can still see the versions in the server docs dropdown in the `Deploy Preview`. Which is strange, not sure why that's happening?
Screen Shot 2021-11-16 at 9 52 37 AM

**Comment by RayOffiah** [comment]
> Hmm, I can still see the versions in the server docs dropdown in the `Deploy Preview`. Which is strange, not sure why that's happening? Screen Shot 2021-11-16 at 9 52 37 AM

Right, just checking.

**Comment by RayOffiah** [comment]
Okay, I get a different drop down.

I think the preview isn't actually doing anything with the version. If you have a look at the file `ui-model.yml` I think that is faking the menu.

**Review by maria-robobug — APPROVED** [review]
👍 LGTM now that I understand what's happening with the left hand nav server versions.
Not sure how we get around that as it can be quite misleading, but that's something to think about in future maybe.

**Comment by RayOffiah** [comment]
The only real way to test it is to build the site locally using the real playbook. It's a bit of a trick; I'm trying it now to make sure it's not a genuine problem I've missed.

**Comment by RichardSmedley** [comment]
The change should be made first to https://github.com/couchbase/docs-site/blob/staging/antora-playbook.yml
and that should show well whether or not there is a missing extra element.  ;)

**Comment by RayOffiah** [comment]
Okay, staging! Got it.

**Comment by maria-robobug** [comment]
See this is why I'm still a bit skeptical about `Deploy Preview` being enough to show things are working ok for production PRs. Especially if we are faking/mocking things in some places.

As @RichardSmedley mentioned, we've got staging to test things. I think we've even done this already there because we had issues with building too many branches, so Simon removed the old 5.x branches there already.

It seems to work fine there: https://docs-staging.couchbase.com/home/server.html

So this should be ok 🤞.

**Comment by RayOffiah** [comment]
I've also removed the older versions of cloud-cli to match up to the server version.

**Review by maria-robobug — APPROVED** [review]

**Pull request merged**
