### PR TITLE
Rayoffiah/adding stem support

### PR DESCRIPTION
**Pull request by RayOffiah**
Adding support for Scientific, Technology, Engineering and Maths formula

### CODE REVIEW

**Comment by RayOffiah** [comment]
These checks failing are a little weird. Have I missed something?

**Comment by maria-robobug** [comment]
Wonder if it would be useful to add the log output stuff in master as well - on staging it has been quite useful for debugging failures. Is it all working on your local build @RayOffiah.

**Comment by RayOffiah** [comment]
> Wonder if it would be useful to add the log output stuff in master as well - on staging it has been quite useful for debugging failures. Is it all working on your local build @RayOffiah.

@maria-robobug 

Yes, that's the weird part. All seems to work fine.

**Comment by mojavelinux** [comment]
Please do not use this package. That is not an official package of the Asciidoctor project and we cannot support that.

If you want STEM support, please follow the approach we have taken for the Asciidoctor docs. See https://github.com/asciidoctor/asciidoctor-docs-ui/blob/main/src/partials/footer-scripts.hbs#L3-L23 This allows you to enable stem support on a per page basis. It does link to the MathJax CDN, though it's possible to bundle MathJax like we do with other libraries.

**Comment by mojavelinux** [comment]
To clarify, MathJax should be integrated into the UI and loaded at runtime. Trying to process STEM at build time (as this package does) is going to impact the build time substantially.

**Comment by RayOffiah** [comment]
> To clarify, MathJax should be integrated into the UI and loaded at runtime. Trying to process STEM at build time (as this package does) is going to impact the build time substantially.

Understood.

I'll close the PR.

**Pull request closed without merging**
