### PR TITLE
upgrade to Antora 3.1

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Note the simplification of exclude-private-content-sources-extension.js and the require path change in source-url-include-processor.js.

We are also recommending using `--lockfile-version=3` when generating package-lock.json as it creates a much smaller file.

**Review by osfameron — APPROVED** [review]
This looks good to me, will discuss testing on staging

**Comment by osfameron** [comment]
Tried this on Staging https://github.com/couchbase/docs-site/pull/649 but had to revert.
Error in Jenkins suggests issues authenticating to some of our repos, so I'm not sure why that is, but have reverted for the meantime

(We're in a team meeting all week, so I may have to wait till Friday to dive in further, but will try to look sooner if I get the chance)

**Comment by mojavelinux** [comment]
I'm curious to see the logs when you get a chance. Nothing should have changed regarding authentication, so I'm puzzled why you are seeing a problem.

**Comment by mojavelinux** [comment]
I'm not sure why the credentials are all of a sudden causing issues, but I reverted the change to lib/exclude-private-content-sources-extension.js since it's tangential to this upgrade anyway.

**Comment by osfameron** [comment]
I don't see any difference in https://docs.antora.org/antora/3.0/playbook/private-repository-auth/#git-credentials-environment-variable between 3.0 and 3.1

We're using the `GIT_CREDENTIALS` env var, as recommended for CI where the env vars are locked down and stored securely in Jenkins.

**Comment by osfameron** [comment]
```
Step 4/4 : RUN addgroup -g $GROUP_ID jenkins && adduser -D -u $USER_ID -G jenkins jenkins && apk add --no-cache --quiet bash ca-certificates git openssh-client python3 && yarn global add --ignore-optional --silent git+https://gitlab.com/opendevise/oss/antora-site-generator-ms#as-extension && yarn global add --ignore-optional --silent asciidoctor-kroki && yarn global add --ignore-optional --silent asciidoctor-external-callout@1.2.0 && apk add --no-cache --quiet --virtual .build-deps py3-pip && pip install --no-cache-dir --quiet --disable-pip-version-check awscli && apk del --no-cache --quiet --purge .build-deps && apk add --no-cache --quiet py3-colorama py3-six py3-urllib3
 ---> Running in 79959c1b24ea
[91mwarning "@antora/site-generator-ms@3.0.0-beta.1" has no binaries
[0m[91mwarning " > asciidoctor-kroki@0.17.0" has unmet peer dependency "@asciidoctor/core@~2.2".
[0m[91mwarning "asciidoctor-kroki@0.17.0" has no binaries
[0m[91mwarning " > asciidoctor-kroki@0.17.0" has unmet peer dependency "@asciidoctor/core@~2.2".
[0m[91mwarning "asciidoctor-external-callout@1.2.0" has no binaries
[0m[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by osfameron** [comment]
Staging playbook defines couchbase-cloud as:

```
  - url: https://git@github.com/couchbasecloud/couchbase-cloud
    branches: [main]
    start_paths: [docs/public, docs/serverless]
```

**Comment by mojavelinux** [comment]
I'm pretty sure the error message is telling us what we need to know. The credentials just aren't being accepted by GitHub. It's possible that they are correct in production, but incorrect in staging. It's hard to know without being able to access the environment in question.

**Comment by leeming** [comment]
Closing this as it was included in part of a merged PR https://github.com/couchbase/docs-site/pull/695

**Pull request closed without merging**
