### PR TITLE
Fork Operator 1.2.0

### PR DESCRIPTION
**Pull request by spjmurray**
DO NOT MERGE UNTIL SOMEONE CONFIRMS THIS BRANCH IS LIVE

### CODE REVIEW

**Comment by spjmurray** [comment]
Obviously CI will totally break so that's not an issue :smiley_cat:

**Comment by spjmurray** [comment]
Or not... what the hell???  Anyway Eric is orchestrating this, let him do what is necessary as there are some ordering constraints he's aware of.

**Comment by eric-schneider** [comment]
@spjmurray My guess is that the site build check is only for production. This PR doesn't break production, but it does break staging.

**Comment by amarantha-k** [comment]
The version number specified in [antora.yml](https://github.com/couchbase/couchbase-operator/blob/master/docs/user/antora.yml) is the same (1.2) in master and 1.2.x branches. This will cause a failure when building the site using the staging playbook as it specifies both these branches.

**Comment by eric-schneider** [comment]
@amarantha-k @spjmurray Since this is a unique situation where we've used the master branch in the Operator repo to publish version 1.2.0 docs, I've split this PR into two other PRs: https://github.com/couchbase/docs-site/pull/81 and https://github.com/couchbase/docs-site/pull/82.
We should close this PR, and instead, merge 81 -> then update the Operator master antora.yml to a newer version -> then merge 82. This will prevent build failures, and prevent unreleased versions from appearing on the production site.

**Comment by amarantha-k** [comment]
Closing as these changes have been merged as part of #81 and #82.

**Pull request closed without merging**
