### PR TITLE
remove archived branches from production site

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@amarantha-k This is staged until we're ready to go live with the archive site. I just wanted to get it ready.

**Comment by mojavelinux** [comment]
@amarantha-k You can find the rewrite rules in this PR. I tried to consolidate it to one regexp location per component, but nginx is processing rules out of order and it never gets hit. So we have to use the longest prefix match instead.

**Comment by mojavelinux** [comment]
I'll need to rebase once the kafka 3.4 change is merged.

**Comment by mojavelinux** [comment]
I believe this is now ready.

**Comment by amarantha-k** [comment]
Quick check on deploy preview looks good. +1 to merge. 
@mojavelinux Will you be merging this as part of archive site roll out?

**Pull request merged**
