### PR TITLE
[NO ISSUE] Build release/7.1 on staging site

### PR DESCRIPTION
**Pull request by simon-dew**

### CODE REVIEW

**Comment by simon-dew** [comment]
Not sure why it hasn't built anything from `docs-analytics`...

**Comment by simon-dew** [comment]
Okay, I don't know why it's not building anything from `docs-analytics`, but it works when I build it locally. I'm tempted to say this is ready for review and see if the problem persists on staging.

**Review by maria-robobug — APPROVED** [review]
Can't see where it says it can't build `docs-analytics`, seem good to me unless I'm missing something!

👍

**Comment by simon-dew** [comment]
> Can't see where it says it can't build `docs-analytics`, seems good to me unless I'm missing something!

If you check out the deploy preview, go to **Server** > **Develop**, Analytics is not listed for any version

**Pull request merged**
