### PR TITLE
upgrade from Antora 3.0.1 to Antora 3.0.3 and simplify extension

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Note that the default site generator package is now named `@antora/site-generator`.

It's no longer possible to create a copy of the playbook object in the `playbookBuilt` event.

**Review by osfameron — APPROVED** [review]
👍

**Comment by mojavelinux** [comment]
I'll follow-up later today with updated information.

**Comment by mojavelinux** [comment]
Superseded by #648.

**Pull request closed without merging**
