### PR TITLE
Update landing pages and playbook file

### PR DESCRIPTION
**Pull request by amarantha-k**

### CODE REVIEW

**Comment by amarantha-k** [comment]
@mojavelinux I'm waiting to confirm that the Cloud landing page builds properly. We should be good to merge this PR soon after.

**Comment by mojavelinux** [comment]
@amarantha-k The only thing that seems off is that the SDKs are not actually laying out as 2 columns.

**Comment by amarantha-k** [comment]
Yes, I see that. Why don't we merge this PR so you can proceed with the next steps, and I'll continue to look into fixing the SDK card layout.

**Comment by mojavelinux** [comment]
Perfect. I'll click merge.

**Pull request merged**
