### PR TITLE
Update es-connector source URL.

### PR DESCRIPTION
**Pull request by jamiltz**
The repo has moved from couchbaselabs to couchbase.

### CODE REVIEW

**Comment by jamiltz** [comment]
@amarantha-k this PR is ready for merging.

**Comment by amarantha-k** [comment]
@jamiltz Looking at the preview (
https://deploy-preview-19--cb-docs-staging.netlify.com/), there is no qualifier that states ES 4.0 as pre-release (DP/Beta). Can you add it please?

**Comment by jamiltz** [comment]
@amarantha-k I have added the master branch on the production playbook. The release date is Friday 12th so we should wait tomorrow to merge this PR. Also removed the `prerelease` property in the component config. cc @dnault @ingenthr

**Comment by dnault** [comment]
@amarantha-k @jamiltz All clear on the dev side. The release notes and download links in the new ES documentation are updated and ready to go live.

**Pull request merged**
