### PR TITLE
update-prod-to-ui-162

### PR DESCRIPTION
**Pull request by RayOffiah**

### CODE REVIEW

**Review by osfameron — COMMENTED** [review]
This looks fine, do we need to test https://github.com/couchbase/docs-site/pull/635 on staging before approving?

**Comment by RayOffiah** [comment]
Yes, I'll do a staging build before trying the prod one.

**Comment by RayOffiah** [comment]
@osfameron 

Yup, runs fine on staging.

**Review by osfameron — APPROVED** [review]

**Comment by RayOffiah** [comment]
Can you merge this? I don't seem to haver permissions to merge this.

**Pull request merged**
