### PR TITLE
dev.adoc as draft replacement for developer.couchbase.com

### PR DESCRIPTION
**Pull request by steveyen**
adding a new page, dev.adoc, as a draft replacement for the landing
page at https://developer.couchbase.com

### CODE REVIEW

**Comment by mojavelinux** [comment]
@steveyen @amarantha-k  The preview of the page is now available at https://5e8cb61a4ef4940007872c77--cb-docs-staging.netlify.com/home/dev.html

We're still working on solving the issue that prevented the preview from being published in the first place. (It was due to a policy change made by Netlify).

**Comment by mojavelinux** [comment]
In order for the preview build to work (pending other infrastructure / permission changes), you'll need to comment out the following content sources in staging-antora-playbook.yml:

```
  - url: https://github.com/couchbase/couchbase-operator.git
    branches: [master, 1.2.x, 1.1.x, 1.0.x]
    start_path: docs/user
  - url: https://github.com/couchbase/docs-connectors-talend.git
    branches: master
  - url: https://github.com/couchbase/docs-analytics.git
    branches: [release/6.5, release/6.0, release/5.5]
  - url: https://github.com/couchbase/backup.git
    branches: [mad-hatter, alice, vulcan]
    start_path: docs
  - url: https://github.com/couchbase/docs-ngdm.git
    branches: [master]
```

This is necessary in order to protect the credentials. The alternative is to either grant trust to your GitHub account or automate this. I'm talking to Amarantha about the best path forward.

**Comment by mojavelinux** [comment]
If you rebase this branch against master, the deploy preview will succeed when you push again.

**Comment by steveyen** [comment]
thanks -- will rebase and repush soon.

in my local-antora-playbook.yml -- indeed, i had to remove those private repos to get my local build to work.  Will leave dorking around with the official staging-antora-playbook.yml to you & Amarantha, as I see that's outside of this local change.

**Comment by mojavelinux** [comment]
Thanks for the follow-up.

If you'd like to get them to work locally, and you have access to those repositories on GitHub, you can do so by following these steps:

1. Create a [personal access token on GitHub](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)
1. Create a ~/.git-credentials file and populate it with the following contents (where `<token>` is your token)

       https://<token>:@github.com

1. Run Antora

Antora will then use the personal access token to authenticate against the private repositories. See https://docs.antora.org/antora/2.2/playbook/private-repository-auth/ for details on how that works, if you're interested.

The other option, as you have figured out, is to remove the private content sources from the playbook.

**Comment by amarantha-k** [comment]
Closing this without merge as I merged the newer PR#168 to staging. Will continue working on the staging branch, and then publish to master.

**Pull request closed without merging**
