### PR TITLE
when adding the data-source-url hint at the point of an include, follow the indentation of the source

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@RayOffiah Can you verify pages that contain source blocks whose indentation should be reset?

**Comment by RayOffiah** [comment]
> @RayOffiah Can you verify pages that contain source blocks whose indentation should be reset?

Will do.

**Review by RayOffiah — APPROVED** [review]

**Comment by RayOffiah** [comment]
Works for me.

**Review by maria-robobug — APPROVED** [review]

**Comment by maria-robobug** [comment]
Looks good:

* Before fix: https://docs.couchbase.com/python-sdk/current/howtos/subdocument-operations.html#durability 
* After fix: https://deploy-preview-442--cb-docs.netlify.app/python-sdk/current/howtos/subdocument-operations.html#durability

**Pull request merged**
